<a href="https://colab.research.google.com/github/Sevostyanka/3_lesson/blob/main/HW_the_last.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#В ячейке ниже представлен код генерирующий DataFrame, которая состоит всего из 1 столбца. 
#Ваша задача перевести его в one hot вид. Сможете ли вы это сделать без get_dummies?

In [9]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [12]:
import random
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame(lst)
data.head()

       0
0  robot
1  human
2  robot
3  robot
4  robot

In [13]:
pd.get_dummies(data[0])

    human  robot
0       0      1
1       1      0
2       0      1
3       0      1
4       0      1
5       1      0
6       1      0
7       1      0
8       0      1
9       0      1
10      0      1
11      1      0
12      1      0
13      0      1
14      0      1
15      1      0
16      1      0
17      0      1
18      1      0
19      1      0

In [15]:
pd.get_dummies(data[0])

    human  robot
0       0      1
1       1      0
2       0      1
3       0      1
4       0      1
5       1      0
6       1      0
7       1      0
8       0      1
9       0      1
10      0      1
11      1      0
12      1      0
13      0      1
14      0      1
15      1      0
16      1      0
17      0      1
18      1      0
19      1      0

In [16]:
data.loc[data[0]=='human', 'human']='1'
data.loc[data[0]=='human', 'robot']='0'
data.loc[data[0]=='robot', 'robot']='1'
data.loc[data[0]=='robot', 'human']='0'
data.head(19)

        0 human robot
0   robot     0     1
1   human     1     0
2   robot     0     1
3   robot     0     1
4   robot     0     1
5   human     1     0
6   human     1     0
7   human     1     0
8   robot     0     1
9   robot     0     1
10  robot     0     1
11  human     1     0
12  human     1     0
13  robot     0     1
14  robot     0     1
15  human     1     0
16  human     1     0
17  robot     0     1
18  human     1     0